var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});

bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});


//thousands of yomama jokes
var yomamaArray =
[
"My mama is so fat that her bellybutton gets home 15 minutes before she does.",
"My mama is so fat that when she was diagnosed with a flesh-eating disease, the doctor gave her ten years to live.",
"My mama is so fat that the National Weather Service names each one of her farts.",
"My mama is so fat that when she wears a yellow raincoat, people yell \"taxi!\"",
"My mama is so fat and dumb that the only reason she opened her email was because she heard it contained spam.",
"My mama is so fat she threw on a sheet for Halloween and went as Antarctica.",
"My mama is so fat that she looked up cheat codes for Wii Fit",
"My mama is so fat that the only exercise she gets is when she chases the ice cream truck.",
"My mama is so fat that she sat on a dollar and squeezed a booger out George Washington\'s nose.",
"My mama is so fat that when she gets in an elevator, it has to go down.",
"My mama is so fat that when her beeper goes off, people think she\'s backing up.",
"My mama is so fat that she has to iron her pants on the driveway.",
"My mama is so fat that she left the house in high heels and came back wearing flip flops.",
"My mama is so fat that people jog around her for exercise.",
"My mama is so fat that she was floating in the ocean and Spain claimed her for the New World.",
"My mama is so fat that when she walked in front of the TV, I missed 3 seasons of Breaking Bad.",
"My mama is so fat that myu have to grease the door frame and hold a twinkie on the other side just to get her through!",
"My mama is so fat that that when she sits on the beach, Greenpeace shows up and tries to tow her back into the ocean...",
"My mama is so fat that when she bungee jumps, she brings down the bridge too.",
"My mama is so fat that when she talks to herself, itgs a long distance call.",
"My mama is so fat that the last time she saw 90210, it was on a scale.",
"My mama is so fat that light bends around her.",
"My mama is so fat that I took a picture of her last Christmas and it\'s still printing!",
"My mama is so fat that when she sat on Wal-Mart, she lowered the prices.",
"My mama is so fat that when she sat on an iphone, it turned into an ipad.",
"My mama is so fat that even god can\'t lift her spirit.",
"My mama is so fat that she gets group insurance.",
"My mama is so fat that she was zoned for commercial development.",
"My mama is so fat that she walked into the Gap and filled it.",
"My mama is so fat that she comes at myu from all directions.",
"My mama is so fat that when she climbed onto a diving board at the beach, the lifeguard told myur dad \"sorry, myu can\'t park here\".",
"My mama is so fat that her cereal bowl came with a lifeguard.",
"My mama is so fat that she looks like shegs smuggling a Volkswagen.",
"My mama is so fat that when she got her shoes shined, she had to take the guygs word for it.",
"My mama is so fat that when she sings, itgs over for everybody.",
"My mama is so fat that when she ran away, they had to use all four sides of the milk carton to display her picture.",
"My mama is so fat that when she was growing up she didngt play with dolls, she played with midgets.",
"My mama is so fat that she uses two buses for roller-blades.",
"My mama\'s so fat she blew up the Deathstar.",
"My mama is so fat that when she goes to a buffet, she gets the group rate.",
"My mama is so fat that she has to put her belt on with a boomerang.",
"My mama is so fat that she broke the Stairway to Heaven.",
"My mama is so fat that she doesngt eat with a fork, she eats with a forklift.",
"My mama is so fat that the last time the landlord saw her, he doubled the rent.",
"My mama is so fat that Weight Watchers wongt look at her.",
"My mama is so fat that the highway patrol made her wear a sign saying \"Caution! Wide Turn\".",
"My mama is so fat that when she sits around the house, she SITS AROUND THE HOUSE!",
"My mama is so fat that when she steps on a scale, it reads \"one at a time, please\".",
"My mama is so fat that she fell in love and broke it.",
"My mama is so fat that when she gets on the scale it says \"We don\'t do livestock\".",
"My mama is so fat that when she tripped on 4th Ave, she landed on 12th.",
"My mama is so fat that God couldn\'t light the Earth until she moved!",
"My mama is so fat that even Bill Gates couldn\'t pay for her liposuction!",
"My mama is so fat that she has to pull down her pants to get into her pockets.",
"My mama is so fat that she was born on the fourth, fifth, and sixth of June.",
"My mama is so fat that she could fall down and wouldngt even know it.",
"My mama is so fat that the sign inside one restaurant says, “Maximum occupancy: 300, or My momma.”",
"My mama is so fat that she puts mamynnaise on aspirin.",
"My mama is so fat that she was born with a silver shovel in her mouth.",
"My mama is so fat that when she hauls ass, she has to make two trips.",
"My mama is so fat that she had to go to Sea World to get baptized.",
"My mama is so fat that her bellybuttongs got an echo.",
"My mama is so fat that when she turns around people throw her a welcome back party.",
"My mama is so fat that her belly button doesngt have lint, it has sweaters.",
"My mama is so fat that a picture of her would fall off the wall.",
"My mama is so fat that when she takes a shower, her feet dongt get wet.",
"My mama is so fat that she puts on her lipstick with a paint-roller!",
"My mama is so fat that she could sell shade.",
"My mama is so fat that I ran around her twice and got lost.",
"My mama is so fat that the shadow of her butt weighs 100 pounds.",
"My mama is so fat that when shegs standing on the corner police drive by and yell, “Hey, break it up.”",
"My mama is so fat that her blood type is Ragu.",
"My mama is so fat that when she runs the fifty-yard dash she needs an overnight bag.",
"My mama is so fat that she cangt even fit into an AOL chat room.",
"My mama is so fat when she goes skydiving she doesn\'t use a parachute to land, she uses a twin-engine plane!",
"My mama is so fat MTX audio\'s subwoofers couldn\'t rattle her bones!",
"My mama is so fat her headphones are a pair of PA speakers connected to a car amplifier.",
"My mama is so fat that she doesngt have a tailor, she has a contractor.",
"My mama is so fat that eating contests have banned her because she is unfair competition.",
"My mama is so fat that she measures 36-24-36, and the other arm is just as big.",
"My mama is so fat that she gets her toenails painted at Luckygs Auto Body.",
"My mama is so fat that when she goes to an amusement park, people try to ride HER!",
"My mama is so fat that when she jumps up in the air she gets stuck!",
"My mama is so fat that she has more Chins than a Chinese phone book!",
"My mama is so fat that she influences the tides.",
"My mama is so fat that when she plays hopscotch, she goes \"New Myrk, L.A., Chicago...\"",
"My mama is so fat that NASA has to orbit a satellite around her!",
"My mama is so fat that when she sits on my face I can\'t hear the stereo.",
"My mama is so fat that they have to grease the bath tub to get her out!",
"My mama is so fat that she\'s on both sides of the family!",
"My mama is so fat that at the zoo, the elephants throw HER peanuts.",
"My mama is so fat myu have to roll over twice to get off her.",
"My mama is so fat that she sets off car alarms when she runs.",
"My mama is so fat that she cant reach into her back pocket.",
"My mama is so fat that she has her own gravity field.",
"My mama is so fat that she stepped on a rainbow and made Skittles.",
"My mama is so fat that the only pictures myu have of her were taken by satellite cameras.",
"My mama is so fat that when she wears a \"Malcolm X\" T-shirt, helicopters try to land on her back!",
"My mama is so fat that it took Usain Bolt 3 years to run around her.",
"My mama so fat that she sweats more than a dog in a chinese restaurant.",
"My mama so fat, that went she stepped in the water, Thailand had to declare another tsunami warning.",
"My mama is so fat that that she cant tie her own shoes.",
"My mama is so fat that when she lays on the beach, people run around yelling Free Willy.",
"My mama is so fat that she uses redwoods to pick her teeth",
"My mama is so fat that she cut her leg and gravy poured out",
"My mama is so fat that she was in the Macygs Thanksgiving Day Parade... wearing ropes.",
"My mama is so fat that she went on a light diet. As soon as itgs light she starts eating.",
"My mama is so fat that shegs half Italian, half Irish, and half American.",
"My mama is so fat that her waist size is the Equator.",
"My mama is so fat that she cangt even jump to a conclusion.",
"My mama is so fat that she uses a mattress for a tampon.",
"My mama is so fat that when she got hit by a bus, she said, \"Who threw that rock at me?\"",
"My mama is so fat that we went to the drive-in and didn\'t have to pay for her because we dressed her up as a Tomyta.",
"My mama is so fat that when she was born, she gave the hospital stretch marks.",
"My mama is so fat that she was cut from the cast of E.T., because she caused an eclipse when she rode the bike across the moon.",
"My mama is so fat that when myu get on top of her myur ears pop.",
"My mama is so fat that she got hit by a car and had to go to the hospital to have it removed.",
"My mama is so fat that she eats \"Wheat Thicks\".",
"My mama is so fat that we\'re in her right now!",
"My mama is so fat that she went to the movie theatre and sat next to evermyne.",
"My mama is so fat that she has been declared a natural habitat for condors.",
"My mama is so fat that when she wants to shake someones hand, she has to give directions!",
"My mama is so fat that even Dora can\'t explore her!",
"My mama is so fat that when she gets on the scale it says \"to be continued\".",
"My mama is so fat that when she goes to a resturant, she looks at the menu and says \"okay!\"",
"My mama is so fat that even Chuck Norris couldn\'t run around her.",
"My mama is so fat that her neck looks like a dozen hot dogs!",
"My mama is so fat that when she bungee jumps she goes straight to hell!",
"My mama is so fat that she\'s got her own area code!",
"My mama is so fat that she looks like she\'s smuggling a Volkswagon!",
"My mama is so fat that she has to buy three airline tickets.",
"My mama is so fat that whenever she goes to the beach the tide comes in!",
"My mama is so fat that she\'s got Amtrak written on her leg.",
"My mama is so fat that her legs are like spoiled milk - white & chunky!",
"My mama is so fat that I had to take a train and two buses just to get on the her good side!",
"My mama is so fat that she wakes up in sections!",
"My mama so fat, all she wants for Christmas is to see her feet.",
"My mama is so fat that when she lies on the beach no one else gets any sun!",
"My mama is so fat that that her senior pictures had to be taken from a helicopter!",
"My mama is so fat that everytime she walks in high heels, she strikes oil!",
"My mama is so fat that she fell and created the Grand Canmyn!",
"My mama is so fat that her butt drags on the ground and kids yell - \"there goes santa claus with his bag of toys!\"",
"My mama is so fat that even her clothes have stretch marks!",
"My mama is so fat that she has to use a VCR as a beeper!",
"My mama is so fat that when she asked for a waterbed, they put a blanket over the ocean!",
"My mama is so fat that she got hit by a parked car!",
"My mama is so fat that they use the elastic in her underwear for bungee jumping.",
"My mama is so fat that when we were playing Call of Duty, I got a 20 kill streak for killing her.",
"My mama is so fat that Dracula got Type 2 Diabetes after biting her neck.",
"My mama is so fat that when she visited Toronto\'s City Hall, she was arrested for attempting to smuggle 500 lbs of crack into Mamyr Rob Ford\'s office.",
"My mama is so fat that when she fell over she rocked herself asleep trying to get up again.",
"My mama is so fat that that when I tried to drive around her I ran out of gas.",
"My mama is so fat that when she went to church and sat on a bible, Jesus came out and said \"LET MY PEOPLE GO!\"",
"My mama is so fat that when she dances at a concert the whole band skips.",
"My mama is so fat that she stands in two time zones.",
"My mama is so fat that she went to the fair and the kids thought she was a bouncy castle.",
"My mama is so fat that when she goes to an all myu can eat buffet, they have to install speed bumps.",
"My mama is so fat that the camera TAKES AWAY 10 lbs from her appearance.",
"My mama is so fat that her sedan can fit 5 people... or just my mama with the front seats removed.",
"My mama is so fat that when she went to seaworld the whales started singing \"We Are Family\".",
"My mama is so fat that she fell out of both sides of her bed.",
"My mama is so fat that the stripes on her pajamas never end.",
"My mama is so fat, Al Gore accuses her of global warning everytime she farts!",
"My mama is so fat that she\'s got every caterer in the city on speed dial!",
"My mama\'s so fat that when she goes on a scale, it shows her own phone number.",
"My mama\'s so fat that she doesn\'t need the internet - she\'s worldwide.",
"My mama\'s so fat that when she goes on a scale, it reads \"lose some weight\".",
"My mama\'s so fat that she doesn\'t get dreams, she gets movies!",
"My mama\'s so fat that when she walks, she changes the earth\'s rotation!",
"My mama is so fat that she uses the entire country of Mexico as her tanning bed.",
"My mama is so ugly that when she went to a beautician it took 12 hours... to get a quote!",
"My mama is so ugly that she looked out the window and got arrested for mooning.",
"My mama is so ugly that people go as her for Halloween.",
"My mama is so ugly that she turned Medusa to stone!",
"My mama is so ugly that the government moved Halloween to her birthday!",
"My mama is so ugly that she scares the roaches away.",
"My mama is so ugly that she scared the crap out of the toilet.",
"My mama is so ugly that... well... look at myu!",
"My mama is so ugly that when she looks in the mirror, the reflection looks back and shakes its head.",
"My mama is so ugly that she looks like she\'s been in a dryer filled with rocks.",
"My mama is so ugly that she makes blind children cry.",
"My mama is so ugly that she climbed the ugly ladder and didn\'t miss a step.",
"My mama is so ugly that the last time I saw something that looked like her, I pinned a tail on it.",
"My mama is so ugly that we put her in the kennel when we go on vacation.",
"My mama is so ugly that her shadow ran away from her.",
"My mama is so ugly that she could scare the flies off a shit wagon.",
"My mama is so ugly that her birth certificate contained an apology letter from the condom factory.",
"My mama is so ugly that that myur father takes her to work with him so that he doesn\'t have to kiss her goodbye.",
"My mama is so ugly that she tried to take a bath and the water jumped out!",
"My mama is so ugly that when she walks down the street in September, people say \"Wow, is it Halloween already?\"",
"My mama is so ugly that her mom had to be drunk to breast feed her.",
"My mama is so ugly that when she walks into a bank, they turn off the surveillence cameras.",
"My mama is so ugly that they didn\'t give her a costume when she auditioned for Star Wars.",
"My mama is so ugly that even Rice Krispies won\'t talk to her!",
"My mama is so ugly that when she uploaded a photo of herself to a computer, it was rejected by the anti-virus software.",
"My mama is so ugly that when she joined an ugly contest, they said \"Sorry, no professionals.\"",
"My mama is so ugly that she could make a freight train take a dirt road.",
"My mama is so ugly that that when she sits in the sand on the beach, cats try to bury her.",
"My mama is so ugly that when she drove past area 51, she was thought to be extraterrestrial life. They took her away never to be seen again.",
"My mama is so ugly that they pay her to put her clothes on in strip joints",
"My mama is so ugly that myu have to tie a steak around her neck so the dog will play with her!",
"My mama is so ugly that just after she was born, her mother said \"What a treasure!\" and her father said \"Yes, let\'s go bury it.\"",
"My mama is so ugly that she made an onion cry!",
"My mama is so ugly that when I last saw a mouth like hers, it had a hook in it.",
"My mama is so ugly that she gets 364 extra days to dress up for Halloween!",
"My mama is so ugly that when she plays Mortal Kombat, Scorpion tells her to \"Stay Over There!\"",
"My mama is so ugly that neither Jacob nor Edward want her on their team.",
"My mama is so ugly that they push her face into dough to make gorilla cookies.",
"My mama is so ugly that when she goes to the therapist, he makes her lie on the couch face down.",
"My mama is so ugly that she gives Freddy Kreuger nightmares.",
"My mama is so ugly that when she walks in the kitchen, the rats jump on the table and start screaming.",
"My mama is so ugly that even Bill Clinton wouldn\'t sleep with her.",
"My mama is so ugly that when she was born, the doctor slapped her AND her parents!",
"My mama is so ugly that she didn\'t get hit with the ugly stick, she got hit by the whole damn tree.",
"My mama is so ugly that she has 7 years bad luck just trying to look at herself in the mirror.",
"My mama is so ugly that she practices birth control by leaving the lights on.",
"My mama is so ugly that she threw a boomerang and it wouldn\'t even come back.",
"My mama is so ugly that she\'d scare the monster out of Loch Ness.",
"My mama is so ugly that it looks like she\'s been bobbing for french fries.",
"My mama is so ugly that her pillow cries at night.",
"My mama is so ugly that people at the circus pay money not to see her.",
"My mama is so ugly that when she looks in the mirror it says \"viewer discretion is advised.\"",
"My mama is so ugly that she can look up a camel\'s butt and scare the hump off of it.",
"My mama is so ugly that when she moved into the projects, all her neighbors chipped in for curtains.",
"My mama is so ugly that Santa pays an elf to drop off her gifts at Christmas.",
"My mama is so ugly that people hang her picture in their cars so their radios don\'t get stolen.",
"My mama is so ugly that I took her to a haunted house and she came out with a job application.",
"My mama is so ugly that if she was a scarecrow, the corn would run away.",
"My mama is so ugly that she could be the poster child for birth control.",
"My mama is so ugly that I took her to the zoo, guy at the door said \"\"",
"My mama is so ugly that when she went to a beautician it took 12 hours... to get a quote!",
"My mama is so ugly that she looked out the window and got arrested for mooning.",
"My mama is so ugly that people go as her for Halloween.",
"My mama is so ugly that she turned Medusa to stone!",
"My mama is so ugly that the government moved Halloween to her birthday!",
"My mama is so ugly that she scares the roaches away.",
"My mama is so ugly that she scared the crap out of the toilet.",
"My mama is so ugly that... well... look at myu!",
"My mama is so ugly that when she looks in the mirror, the reflection looks back and shakes its head.",
"My mama is so ugly that she looks like she\'s been in a dryer filled with rocks.",
"My mama is so ugly that she makes blind children cry.",
"My mama is so ugly that she climbed the ugly ladder and didn\'t miss a step.",
"My mama is so ugly that the last time I saw something that looked like her, I pinned a tail on it.",
"My mama is so ugly that we put her in the kennel when we go on vacation.",
"My mama is so ugly that her shadow ran away from her.",
"My mama is so ugly that she could scare the flies off a shit wagon.",
"My mama is so ugly that her birth certificate contained an apology letter from the condom factory.",
"My mama is so ugly that that myur father takes her to work with him so that he doesn\'t have to kiss her goodbye.",
"My mama is so ugly that she tried to take a bath and the water jumped out!",
"My mama is so ugly that when she walks down the street in September, people say \"Wow, is it Halloween already?\"",
"My mama is so ugly that her mom had to be drunk to breast feed her.",
"My mama is so ugly that when she walks into a bank, they turn off the surveillence cameras.",
"My mama is so ugly that they didn\'t give her a costume when she auditioned for Star Wars.",
"My mama is so ugly that even Rice Krispies won\'t talk to her!",
"My mama is so ugly that when she uploaded a photo of herself to a computer, it was rejected by the anti-virus software.",
"My mama is so ugly that when she joined an ugly contest, they said \"Sorry, no professionals.\"",
"My mama is so ugly that she could make a freight train take a dirt road.",
"My mama is so ugly that that when she sits in the sand on the beach, cats try to bury her.",
"My mama is so ugly that when she drove past area 51, she was thought to be extraterrestrial life. They took her away never to be seen again.",
"My mama is so ugly that they pay her to put her clothes on in strip joints",
"My mama is so ugly that myu have to tie a steak around her neck so the dog will play with her!",
"My mama is so ugly that just after she was born, her mother said \"What a treasure!\" and her father said \"Yes, let\'s go bury it.\"",
"My mama is so ugly that she made an onion cry!",
"My mama is so ugly that when I last saw a mouth like hers, it had a hook in it.",
"My mama is so ugly that she gets 364 extra days to dress up for Halloween!",
"My mama is so ugly that when she plays Mortal Kombat, Scorpion tells her to \"Stay Over There!\"",
"My mama is so ugly that neither Jacob nor Edward want her on their team.",
"My mama is so ugly that they push her face into dough to make gorilla cookies.",
"My mama is so ugly that when she goes to the therapist, he makes her lie on the couch face down.",
"My mama is so ugly that she gives Freddy Kreuger nightmares.",
"My mama is so ugly that when she walks in the kitchen, the rats jump on the table and start screaming.",
"My mama is so ugly that even Bill Clinton wouldn\'t sleep with her.",
"My mama is so ugly that when she was born, the doctor slapped her AND her parents!",
"My mama is so ugly that she didn\'t get hit with the ugly stick, she got hit by the whole damn tree.",
"My mama is so ugly that she has 7 years bad luck just trying to look at herself in the mirror.",
"My mama is so ugly that she practices birth control by leaving the lights on.",
"My mama is so ugly that she threw a boomerang and it wouldn\'t even come back.",
"My mama is so ugly that she\'d scare the monster out of Loch Ness.",
"My mama is so ugly that it looks like she\'s been bobbing for french fries.",
"My mama is so ugly that her pillow cries at night.",
"My mama is so ugly that people at the circus pay money not to see her.",
"My mama is so ugly that when she looks in the mirror it says \"viewer discretion is advised.\"",
"My mama is so ugly that she can look up a camel\'s butt and scare the hump off of it.",
"My mama is so ugly that when she moved into the projects, all her neighbors chipped in for curtains.",
"My mama is so ugly that Santa pays an elf to drop off her gifts at Christmas.",
"My mama is so ugly that people hang her picture in their cars so their radios don\'t get stolen.",
"My mama is so ugly that I took her to a haunted house and she came out with a job application.",
"My mama is so ugly that if she was a scarecrow, the corn would run away.",
"My mama is so ugly that she could be the poster child for birth control.",
"My mama is so ugly that I took her to the zoo, guy at the door said \"Thanks for bringing her back.\"",
"My mama is so ugly that when she went to Taco Bell evermyne ran for the border.",
"My mama is so ugly that her face is blurred on her driver\'s license.",
"My mama is so ugly that when she walked out of her house, the neighbours called animal control.",
"My mama is so ugly that the FCC requires her face to be blurred when she\'s on TV, because of decency rules.",
"My mama is so ugly that a sculpture of her face is used when torturing prisoners at Guantanamo Bay.",
"My mama is so ugly that government intelligence agencies have to pixelize her face when spying on her.",
"My mama is so ugly that she\'s never seen herself \'cause the mirrors keep breaking.",
"My mama is so ugly that it looks like someone did the stanky leg dance on her face.",
"My mama is so ugly that when she was born she was put in an incubator with tinted windows.",
"My mama is so ugly that she put the Boogie Man out of business!",
"My mama is so ugly that she made Barack Obama lose hope!",
"My mama was such an ugly baby that her parents had to feed her with a slingshot.",
"My mama is like a hockey player, she only showers after three periods.",
"My mama is like a chicken coop, cocks fly in and out all day.",
"My mama has so many teeth missing, that it looks like her tongue is in jail.",
"My mama\'s mouth is so big that she speaks in surround sound.",
"My mama is so grouchy that the McDonalds she works in doesn\'t even serve Happy Meals.",
"Myu suck... my mama does too, but she charges.",
"My mama is like a paper towel, she picks up all kinds of slimy wet stuff.",
"My mama is like Bazooka Joe, 5 cents a blow.",
"My mama is like a telephone, even a 3 year old can pick her up.",
"My mama is like a Christmas tree, everybody hangs balls on her.",
"My mama is like the sun, look at her too long and myu\'ll go blind.",
"My mama is like a library, she\'s open to the public.",
"My mama is like a fine restaurant, she only takes deliveries in the rear.",
"My mama is like an ATM, open 24 hours.",
"My mama is like a bowling ball... round, heavy, and myu can fit three fingers in.",
"My mama is like a basketball hoop, everybody gets a shot.",
"My mama is like a Discover card, she gives cash back.",
"My mama is like a championship ring, everybody puts a finger in her.",
"My mama is like Dominoes Pizza, one call does it all.",
"My mama is like a microwave, press one button and she\'s hot.",
"My mama is like a mail box, open day and night.",
"My mama is like a bowling ball, she always winds up in the gutter.",
"My mama is like a bus, guys climb on and off her all day long.",
"My mama is like a door knob, everybody gets a turn.",
"My mama is like a light switch, even a little kid can turn her on.",
"My mama\'s such a ho that \"who\'s myur daddy?\" is a multiple-choice question.",
"Myu\'ll never be the man My mama was.",
"My mama... \'nuff said.",
"My mama is so lazy that she thinks a two-income family is where my daddy has two jobs.",
"My mama is so lazy that she\'s got a remote control just to operate her remote!",
"My mama\'s arms are so short that she has to tilt her head to scratch her ear.",
"My mama\'s lips are so big that Chapstick had to invent a spray.",
"My mama is so lazy that she came in last place in a recent snail marathon.",
"What\'s the difference between my momma and a walrus? One has whiskers and smells of fish... the other one is a walrus!",
"My mama is missing a finger and can\'t count past nine.",
"My mama is so flat that she makes the walls jealous!",
"My mama\'s gums are so black that she spits Myo-hoo.",
"It took my mama 10 tries to get her drivers license - she couldn\'t get used to the front seat!",
"My mama\'s so fat that when she asked me \"what\'s up?\" I said \"myur weight!\"",
"My mama is twice the man myu are.",
"My mama\'s head is so small that she got her ear pierced and died.",
"My mama is cross-eyed and watches TV in stereo.",
"My mama is so stupid that she was born on Independence Day and can\'t remember her birthday.",
"My mama\'s head is so small that she uses a tea-bag as a pillow.",
"My mama\'s face is so wrinkled, that she has to screw her hat on.",
"My mama\'s hips are so big that people set their drinks on them.",
"My mama\'s hair is so nappy that she has to take Tylenol just to comb it.",
"My mama\'s feet are so big that her shoes need to have license plates on them!",
"My mama\'s so lonely that she buys hot dogs and nuts wishing she could have sex with them.",
"My mama is so bald that even a wig wouldn\'t help!",
"My mama is so bald that myu can see what\'s on her mind.",
"My mama is so bald that she took a shower and got brain-washed!",
"My mama\'s teeth are so yellow that when she smiles evermyne sings \"We\'re Walking on Sunshine.\"",
"My mama is like a slaughter house - everybody\'s hanging their meat up in her.",
"My mama is like the new AOL 4.0: Fun, Fast, Easy and Free!",
"My mama is like a carpenter\'s dream - flat as a board and easy to nail.",
"My mama is like Humpty Dumpty - First she gets humped, then she gets dumped.",
"My mama is like a bag of potato chips, \"Free-To-Lay.\"",
"My mama is like a turtle - once she\'s on her back she\'s fucked.",
"My mama is like a fan - she\'s always blowing someone.",
"My mama is like Pizza Hut - if she isn\'t there in 30 minutes... it\'s Free!",
"My mama is like a goalie - she only changes her pads after three periods.",
"My mama is like a gas station - myu gotta pay before myu pump!",
"My mama is like Sprint - 10 cents a minute anywhere in the country.",
"My mama is like a Chinese restaurant - All myu can eat for only $9.95!",
"My mama smells so bad that the doctor diagnosed her with breath cancer.",
"My mama\'s breath smells so bad that when she yawns her teeth duck out of the way.",
"What\'s the difference between my mama and a Lay-Z-Boy? One\'s soft, squishy, and always has someone in it. The other is a chair.",
"What\'s the difference between my mama and a 747? About 20 pounds.",
"My mama\'s like a shotgun, one cock and she blows.",
"My mama\'s like the Bermuda Triangle, they both swallow a lot of seamen.",
"My mama\'s like cake mix, 15 servings per package!",
"My mama\'s like a 5 foot tall basketball hoop, it ain\'t that hard to score.",
"My mama\'s like a vacuum cleaner... she sucks, blows, and then gets laid in the closet.",
"My mama\'s like the Pillsbury dough boy - everybody pokes her.",
"My mama\'s like a brick, dirty, flat on both sides, and always getting laid by Mexicans.",
"My mama\'s like a nickel, she ain\'t worth a dime.",
"My mama\'s like a streetlamp, myu can find her turned on at night on any street corner.",
"My mama\'s like a telephone booth, open to the public, costs a quarter, and guys go in and out all day.",
"My mama\'s like a Reese\'s Peanut Butter Cup, there\'s no wrong way to eat her.",
"My mama\'s like a postage stamp, myu lick her, stick her, then send her away.",
"My mama\'s like a screen door, after a couple of bangs she loosens up.",
"My mama\'s like a dollar bill, she gets handled all across the country.",
"My mama\'s like school at 3 o\'clock... children keep coming out and nobody can remember all the fathers.",
"My mama\'s like a bowling ball, she gets picked up, fingered, thrown down the gutter, and she still comes back for more.",
"My mama\'s like a set of speakers - loud, ugly, lives in a box, and myu can turn her up, down, on, and off.",
"My mama\'s like a birthday cake, everybody gets a piece.",
"My mama\'s like 7-Eleven - open all night, hot to go, and for 89 cents myu can get a slurpy.",
"My mama\'s like a vacuum cleaner - a real good suck.",
"My mama\'s like a Snickers bar, packed with nuts.",
"My mama\'s like a race car driver - she burns a lot of rubbers.",
"My mama\'s like a parking garage, three bucks and myu\'re in.",
"My mama\'s like a pool table, she likes balls in her pocket.",
"My mama\'s got 1 toe & 1 knee and they call her Tony.",
"My mama\'s got a \"wait\" problem, she can\'t wait to eat.",
"My mama\'s got a 4 dollar weave and don\'t know when to leave.",
"My mama\'s teeth are so yellow, when she smiles it looks like a Kraft Singles pack.",
"My mama\'s got Play-Doh teeth.",
"My mama\'s like the Panama Canal, vessels full of seamen pass through her everyday.",
"My mama likes to applaud, \'cause she\'s got clap",
"My mama\'s got 1 leg longer than the other so they call her call her hip hop.",
"My mama\'s got an eating disorder, she be eating dis order, dat order, she be eating all the damn orders!",
"My mama sucks so much dick her butt chin turned into a nut chin!",
"My mama\'s got more chins than a Chinese phone book.",
"My mama\'s like a bungee cord... 100 dollars for 30 seconds and if that rubber breaks, myur ass is dead!",
"My mama\'s like a squirrel, she\'s always got some nuts in her mouth.",
"My mama\'s like a refrigerator, evermyne puts their meat in her.",
"My mama\'s like a tricycle, she\'s easy to ride.",
"my mamas like a hardware store. 25 cents a screw.",
"My mama\'s like mustard, she spreads easy.",
"My mama\'s like peanut butter: brown, creamy, and easy to spread.",
"My mama\'s like McDonalds... Billions and Billions served.",
"My mama\'s like an elevator, guys go up and down on her all day.",
"My mama\'s like a railroad track, she gets laid all over the country.",
"My mama\'s like lettuce, 25 cents a head.",
"My mama\'s got an eagle\'s nest wig.",
"My mama\'s twice the man myu are.",
"My mama\'s got more crust than a bucket of Kentucky Fried Chicken.",
"My mama\'s got more weave than a dog in traffic.",
"My mama\'s only got one finger and runs around stealing key rings.",
"My mama\'s got a peanut butter wig with jelly sideburns.",
"My mama\'s got a leather wig with suede sideburns.",
"My mama got hit upside the head with an ugly stick.",
"My mama\'s got so much weave, when a fly goes by her hair swats at it.",
"My mama\'s got no ears and was trying on sunglasses.",
"My mama\'s got so much weave, AT&T uses her extensions as backup lines.",
"My mama\'s got so much dandruff, she needs to defrost it before she combs her hair.",
"My mama\'s so bald that I can tell fortunes on her head.",
"My mama\'s so bald that myu could draw a line down the middle of her head and it would look like my ass.",
"My mama\'s so bald that when she goes to bed, her head slips off the pillow.",
"My mama\'s so bald that when she braids her hair, it looks like stitches.",
"my mama\'s breath is so stanky, she eats odour eaters.",
"My mama\'s like an iPod, fun to touch!",
"My mama\'s got one leg and people call her Ilene.",
"My mama\'s been on welfare so long that her picture is on food stamps.",
"My mama\'s like Wal-Mart... She\'s got different discounts everyday.",
"My mama\'s so hunchbacked, she has to look up to tie her shoes.",
"My mama\'s nostrils are so huge she makes Patrick Ewing jealous.",
"My mama\'s so hunchbacked, she has to wear goggles to wash dishes.",
"My mama\'s so hunchbacked, she can stand on her feet and her head at the same time.",
"My mama\'s so hunchbacked, she hits her head on speed bumps.",
"My mama\'s so fat that the Sorting Hat put her in all four houses!",
"My mama\'s so fat that a wingardium leviosa spell couldn\'t lift her.",
"My mama\'s so fat, she makes Hagrid look like \"Mini-me\".",
"My mama\'s so fat, she tried to eat Cornelius Fudge.",
"My mama\'s so ugly, even a dementor wouldn\'t kiss her!",
"My mama\'s so fat the Sorting Hat assigned her to the House of Pancakes.",
"My mama\'s so old, she used to babysit Dumbledore.",
"My mama\'s so stupid, she thinks Sirius Black is a hip hop station on satellite radio.",
"My mama\'s so ugly that the whomping willow saw her and died.",
"My mama\'s so stupid she thinks Patronus is a kind of Tequlia.",
"My Mama\'s so fat, her Patronus is a Double-Whopper with Cheese.",
"My mama\'s so nasty, the Forbidden Forrest was named after her.",
"My mama\'s the reason that Dumbledore turned gay.",
"My mama\'s so old, her boobs look like two upside down Sorting Hats!",
"My mama\'s so fat, she used the invisibility cloak as a bib.",
"My Mama\'s so ugly, everybody calls her \"She-Who-Must-Not-Be-Naked\"",
"My mama\'s so fat that even the Dementors can\'t suck her soul out in one sitting.",
"My mama\'s so pasty, she makes Ron Weasely look like George Hamilton.",
"My mama\'s so fat, she looked in the mirror of Erised and saw a ham!",
"My mama\'s so old she gave Nicholas Flamel his first kiss.",
"My mama\'s so ugly that the Dementor\'s Kiss was swapped out for a hearty handshake and a promise to give her a call sometime.",
"My mama\'s so stupid, she drowned in a pensieve",
"My mama\'s so dumb she thought that she could talk to snakes if she put parsley on her tongue",
"My mama\'s so nasty, every pair of her panties has the Dark Mark on them.",
"My mama\'s so fat that if she confronted a boggart it would morph into a treadmill.",
"My Mama\'s so ugly that even Voldemort won\'t say her name.",
"My Mama\'s so poor she can\'t even afford a Gringotts account.",
"My mama\'s so fat that the sorting hat couldn\'t decide where to put her - she couldn\'t fit in any of the houses!!",
"My mama\'s the only mute prostitue in Hogsmeade. They call her \"dumb-le-whore\"!",
"My mama\'s so fat, she ate the Death Eaters.",
"My mama\'s so masculine that Dumbledore would sleep with her!",
"My mama\'s so nasty that the order of the phoenix was \"stay away from that woman!\"",
"My mama\'s so poor that Dobby gave her a sock to keep her foot warm.",
"My mama\'s such a tramp that she\'s given more rides than the Hogwarts Express!",
"My mama\'s so fat even Grawp can\'t pick her up!",
"My mama\'s so smelly, Bertie Bott made her his next jelly bean flavor.",
"My mama\'s so fat that it takes two boggarts to shape-shift into her!",
"My mama\'s so ugly that she lost a beauty contest to Mountain Troll.",
"My mama\'s so ugly that when the bassalisk snuck up on her and saw her face, HE dropped dead.",
"My mama\'s breath is the secret ingredient in the Weasly\'s Butterscotch Barf-ies.",
"My mama\'s so ugly that when she walked into Gringotts Wizarding Bank, they gave her a job application.",
"My mama\'s so ugly she turned the Basilisk to stone.",
"My mama\'s such a tramp that she\'s like a quidditch broomstick - evermyne gets a ride.",
"My mama\'s so skanky that the reason myu\'re called a Half-Blood Prince is because she has no idea who myur father is!",
"My mama\'s so dumb that a stupify spell actually made her smarter.",
"My mama\'s so stanky that not even dobby would accept one of her socks.",
"My mama\'s so fat that even her Quidditch robes have stretch marks.",
"My mama\'s so old she makes Dumbledore look like a teenager.",
"My mama\'s so fat they\'d have to use transfiguration to sneak her through the hole in the Gryffindor Tower.",
"Ya mama\'s so fat, her wand is a Slim Jim.",
"My mama\'s so fat the core of her wand has a creame filling.",
"My mama\'s so ugly that Voldemort took one look at her and killed HIMSELF!\"",
"My mama\'s so poor she had to go to the Weasley\'s for a loan.",
"My mama\'s so ugly, she thought that Hogwarts were the growth on her thigh.",
"My mama\'s so ugly that as a baby they had to use the Confundus Charm so the family would play with her.",
"My mama\'s such a ho that she lets ANMyNE enter her \"chamber of secrets\".",
"My mama\'s so ugly she scares the Dementors away.",
"My mama\'s so ugly that when she asked Crabbe to take her to the Yule Ball, he decided to go with Goyle instead!",
"My mama\'s so fat that a $700 billion bailout would only keep her fed for a week.",
"My mama\'s so fat that the housing bubble popped because she sat on it!",
"My mama\'s so stupid, she thinks the G8 is a Value Meal at McDonald\'s.",
"My mama\'s so fat that she supported the bailout just because she wanted a \'barrel of pork\'.",
"My mama\'s so stupid that she thinks sub-prime is a way to cut steak.",
"My mama\'s so fat that even Mitt Romney couldn\'t afford to take her out to dinner!",
"My mama\'s so fat that her biography is called \"The Audacity of Hardee\'s\".",
"My mama\'s so greasy that her face could free the U.S. from its dependence on foreign oil.",
"My mama\'s so fat that Sarah Palin can see her from her house.",
"My mama\'s so fat that Sarah Palin can\'t see Russia anymore!.",
"My mama\'s so ugly that myu could put lipstick on a pig and it would look ten times better than her!",
"My mama\'s so fat that \"ACORN\" registered her to vote eight times!",
"My mama is so dark that she spits chocolate milk!",
"My mama is so dark that she went to night school and was marked absent!",
"My mama is so dark that she has to wear white gloves when she eats Tootsie Rolls to keep from eating her fingers.",
"My mama is so dark that when she goes swimming it looks like an oil spill.",
"My mama is so dark that her ass looks like two tires.",
"My mama is so dark that she drinks water and pees coffee.",
"My mama is so dark that when she puts on yellow lipstick, she looks like a cheese burger.",
"My mama is so dark that she could show up naked to a funeral.",
"My mama is so dark that she bleeds molasses.",
"My mama is so dark that she looks like a picture of outer-space with no stars... except when she smiles.",
"My mama is so dark that when she goes outside, the streetlights turn on.",
"My mama is so dark that she got her tattoo done in chalk.",
"My mama is so dark that when she puts lotion on her legs it looks like she has on patent leather pants.",
"My mama is so dark that when the police shot at her, the bullets came back for flashlights.",
"My mama is so dark that she was riding a motorcycle and got a ticket for tinted windows.",
"My mama is so dark that when she smiles at night she looks like a pack of floating Chicklets.",
"My mama is so dark that when her eyes are red she looks like a beeper.",
"My mama is so dark that her nickname is midnight.",
"My mama is so dark that she makes asphalt look grey.",
"My mama is so dark that that she can leave fingerprints on charcoal.",
"My mama\'s so fat that even the Death Star couldn\'t blow her up!",
"My mama\'s so fat that Spock couldn\'t find a pressure point to perform the Vulcan Death Grip on her.",
"My mama\'s so ugly that Wuher said \'We don\'t serve myur kind here\'.",
"My mama\'s so fat the odds against not finding her fat are approximately 3,720 to 1.",
"My mama\'s so fat that she thought the opening line of Kirk\'s monologue was \"Spice, the final Frontier...\"",
"My mama\'s so stupid that when the borg had to choose between assimilating her and a tree, they chose the tree.",
"My mama\'s so fat that if she were placed beside a changeling during regeneration, no one would know the difference.",
"My mama\'s so fat that she tried to fly through a temporal anomoly but she didn\'t fit.",
"My mama\'s so fat she makes Riker\'s belly look 3 atoms thick.",
"My mama\'s so fat that when she tried to captain a galaxy class they had to separate the saucer so she could fit.",
"My mama\'s so fat that she makes the USS Enterprise look like a micro machines racer.",
"My mama\'s so flatulent that she forced the Mustafarians to wear masks!",
"My mama\'s so dumb that she tried to rent a car from The Enterprise.",
"My mama\'s so fat that Dexster Jettster mistook her for his wife.",
"My mama\'s so ugly that the term \'bantha poodoo\' wasn\'t used metaphorically with reference to her.",
"My mama\'s so fat that only half her body was able to come out frozen from the carbon freezing chamber in Cloud City.",
"My mama\'s so ugly that Dr. Evazan looks like a male supermodel next to her.",
"My mama\'s so fat that when she beams to a ship, the ship beams inside of her.",
"My mama\'s so such a ho that she slept with me... therefore, I AM MyUR FATHER!",
"My mama\'s so dumb that when she found a vulcan, she tried to call Santa to take him back to the north pole.",
"My mama\'s so fat that the passengers of the Millenium Falcon mistook her for a small moon.",
"My mama\'s so fat that Gardulla the Hutt had a boost in self-esteem after seeing her.",
"My mama\'s so ugly that she made doctor McCoy say \"Damnit Jim, I\'m a doctor, not a Zoologist!\"",
"My mama\'s so fat that she fell to the dark side and couldn\'t get back up.",
"My mama\'s so fat that if she was thrown into the second Death Star\'s reactor core, she could have blown up the entire Imperial fleet.",
"My mama\'s so fat that the Kaminoans couldn\'t use her as a host for clones since they couldn\'t pierce her skin deep enough to draw blood.",
"My mama\'s so weak-minded that I got her to lead me to Jabba without using a jedi mind trick!",
"My mama\'s so fat that she caused Kamino to flood when her water broke.",
"My mama\'s so ugly that she\'s probably a Shi\'ido Clawdite that stays in her regular form all the time.",
"My mama\'s so fat that her lack of balance caused her to stumble into an Utapau sinkhole.",
"My mama\'s so fat that she crushed Boga as soon as she mounted her.",
"My Mama\'s so fat, that in an attempt to beam her up, the ship ended up being pulled down to the surface.",
"My Mama\'s so ugly even Data would need special eye googles to look at her.",
"My mama is so hairy that the only language she can speak is wookie.",
"My mama\'s so ugly her Kazon hairdo is an improvement!",
"My Mama\'s so ugly even a Ferengi would dress her in clothes.",
"My mama\'s so old even Guinan refers to her as \"old bag\".",
"My Mama\'s so fat that when she walks into a room the replicators stop working.",
"My Mama\'s so fat, Data feels strong emotions of disgust and self-terminates.",
"My Mama\'s so stupid the Borg wouldn\'t assimilate her!",
"My Mama\'s so fat she wears her own inertia dampener.",
"My Mama\'s so ugly she did the truly impossible: she made Captain James T Kirk\'s penis go limp.",
"My Mama\'s so fat, she managed to contain a warp core breach.",
"My Mama\'s so fat, she got stuck trying to enter the Nexus.",
"My Mama\'s so fat, when she fell over, she punched a hole in the fabric of space/time.",
"My mama\'s so fat that when she stepped on the scale, her weight was OVER 9000!!!",
"My Mama\'s so fat, she walked in front of the TV and I missed three seasons of Inuyasha!",
"My mama\'s so fat, Naruto couldnt make enough clones to see all sides of her.",
"My mama\'s so ugly, she can\'t even get tentacle raped.",
"My mama\'s so ugly, even Tamaki wouldn\'t hit on her.",
"My mama\'s so fat that the Dragon Ball Z crew uses her to make craters on set.",
"My mama\'s so ugly, she\'s the real reason sasuke left the village.",
"My mama\'s so fat that when she sat down on a park bench, she caused the Naruto timeskip.",
"My mama\'s so ugly that she\'s like a Death Note. Get someone to look at her, and they\'ll die!",
"My mama\'s so ugly, Jiraiya saw her and turned gay!",
"My mama\'s so hairy Naruto thought she was a Summon.",
"My mama\'s so fat, she scared L into giving up all sweets.",
"My mama\'s so ugly that she made Spike Spiegel choke on his cigarette",
"My mama\'s so ugly that she makes Sailor Bubba feel dirty.",
"My mama\'s so fat that she cant even fit in the expanding plug suit.",
"My mama\'s so ugly that she made Loz cry.",
"My mama\'s so dumb that when she was handed the death note, she thought they were asking for her autograph.",
"My mama\'s so fat that she broke the HP limit!",
"My mama\'s so hairy and ugly that she got used as Ashitare\'s stunt double.",
"My mama\'s so stupid she makes Tristan look like Einstein!",
"My mama\'s so fat, she makes Vash look anorexic!",
"My mama\'s so hairy that she has to go to Furfest to meet a man.",
"My mama\'s breath is so nasty that it chases away Miasma.",
"My mama\'s so round that she makes a Pokéball look flat!",
"My mama\'s so ugly, Saya thought she was a Chiropteran.",
"My mama\'s so dumb, she failed out of Cromartie High School.",
"My mama\'s so old and fat they use her wrinkles as set terrain for Dragon Ball Z.",
"My mama\'s nosehairs are so long that they make Bobobo jealous!",
"My mama\'s so fat that she was mistaken for Mt. Fuji at the Sakura festival.",
"My mama\'s so fat she makes a Snorlax look like a chihuahua!",
"My mama\'s so ugly that when Nozomu Itoshiki saw her, he didn\'t even bother with his \"ZETSUBOUSHITA!\" speech - he skipped straight to hanging himself.",
"My mama\'s so fat that it took the entire Dragon Ball Z crew 1 week just to lift her off the ground.",
"My mama\'s cosplay is so bad that she got beat by a Narutard in the masquerade!",
"My mama\'s so ugly that when Kakashi looked directly at her, he lost an eye.",
"My mama\'s so fat that she tried to eat someone dressed as a box of Pocky!",
"My mama\'s so ugly that she makes Orochimaru look beautiful.",
"My mama\'s so fat, Choji told her to lose weight.",
"My mama is so old that her birth certificate says \"expired\" on it.",
"My mama is so old that that when she was in school there was no history class.",
"My mama is so old that I told her to act her own age, and she died.",
"My mama is so old that she knew Burger King while he was still a prince.",
"My mama is so old that her social security number is 1.",
"My mama is so old that her birth certificate is written in Roman numerals.",
"My mama is so old that she has Adam & Eve\'s autographs.",
"My mama is so old that she co-wrote the Ten Commandments.",
"My mama is so old that she has an autographed bible.",
"My mama is so old she remembers when the Mayans published their calendar.",
"My mama is so old that the candles cost more than the birthday cake.",
"My mama is so old that when she farts, dust comes out.",
"My mama is so old that she owes Fred Flintstone a food stamp.",
"My mama is so old that she drove a chariot to high school.",
"My mama is so old that she took her drivers test on a dinosaur.",
"My mama is so old that she DJ\'d at the Boston Tea Party.",
"My mama is so old that she walked into an antique store and they kept her.",
"My mama is so old that she baby-sat for Jesus.",
"My mama is so old that she knew Mr. Clean when he had an afro.",
"My mama is so old that she knew the Beetles when they were the New Kids on the Block.",
"My mama is so old that when God said \"Let there be light\" she was there to flick the switch.",
"My mama is so old that she needed a walker when Jesus was still in diapers.",
"My mama is so old that when Moses split the red sea, she was on the other side fishing.",
"My mama is so old that she learned to write on cave walls.",
"My mama is so old that her memory is in black and white.",
"My mama is so old that she\'s mentioned in the shout out at the end of the bible.",
"My mama is so old that she planted the first tree at Central Park.",
"My mama is so old that she sat next to Jesus in third grade.",
"My mama is so old that she has a picture of Moses in her yearbook.",
"My mama is so old that she knew Cap\'n Crunch while he was still a private.",
"My mama is so old that she called the cops when David and Goliath started to fight.",
"My mama is so old that when she was born, the Dead Sea was just getting sick.",
"My mamags so old, when she breast feeds, people mistake her for a fog machine.",
"My mama is so old that when she was myung rainbows were black and white.",
"My mama is so old that she was a waitress at the Last Supper.",
"My mama is so old that she owes Jesus a dollar.",
"My mama is so old that she ran track with dinosaurs.",
"My mama is so stupid that it took her 2 hours to watch 60 Minutes!",
"My mama is so stupid that when myur dad said it was chilly outside, she ran out the door with a spoon.",
"My mama is so stupid that when she saw the \"Under 17 not admitted\" sign at a movie theatre, she went home and got 16 friends.",
"My mama is so stupid that when she went for a blood test, she asked for time to study.",
"My mama is so stupid that she got locked in a grocery store and starved!",
"My mama is so stupid that myu have to dig for her IQ!",
"My mama is so stupid that she tripped over a cordless phone!",
"My mama is so stupid that she sold her car for gas money!",
"My mama is so stupid that she told evermyne that she was \"illegitimate\" because she couldn\'t read.",
"My mama is so stupid that that she tried to put M&M\'s in alphabetical order!",
"My mama is so stupid that she took the Pepsi challenge and chose Dr. Pepper.",
"My mama is so stupid that she thought Delta Airlines was a sorority.",
"My mama is so stupid that she thinks Fleetwood Mac is a new hamburger at McDonalds!",
"My mama is so stupid that she bought a videocamera to record cable tv shows at home.",
"My mama is so stupid that when she read on her job application to not write below the dotted line she put \"OK\".",
"My mama is so stupid that she thought Grape Nuts was an STD.",
"My mama is so stupid that she spent twenty minutes lookin\' at an orange juice box because it said \"concentrate\".",
"My mama is so stupid that she asked me what yield meant, I said \"Slow down\" and she said \"What... does.... yield... mean?\"",
"My mama is so stupid that she thought Dunkin\' Donuts was a basketball team!",
"My mama is so stupid that she put a phone up her ass and thought she was making a booty call.",
"My mama is so stupid that she thinks Tiger Woods is a forest in India.",
"My mama is so stupid that she put on her glasses to watch 20/20.",
"My mama is so stupid that she climbed over a glass wall to see what was behind it.",
"My mama is so stupid that she failed a survey.",
"My mama is so stupid that she stopped at a stop sign and waited for it to say go.",
"My mama is so stupid, she went to the aquarium to buy a Blu-Ray.",
"My mama is so stupid that I told her I was reading a book by Homer and she asked if I had anything written by Bart.",
"My mama is so stupid that she tried to commit suicide by jumping out of the basement window.",
"My mama is so stupid that she needs twice as much sense to be a half-wit.",
"My mama is so stupid that she thought brownie points were coupons for a bake sale.",
"My mama is so stupid that when the computer said \"Press any key to continue\", she couldn\'t find the \'Any\' key.",
"My mama is so stupid that she thought Tupac Shakur was a Jewish holiday.",
"My mama is so stupid that when I was drowning and yelled for a life saver, she said \"Cherry or Grape?\"",
"My mama is so stupid that she sat in a tree house because she wanted to be a branch manager.",
"My mama is so stupid that I saw her jumping up and down, asked what she was doing, and she said she drank a bottle of medicine and forgot to shake it.",
"My mama is so stupid that when she locked her keys in the car, it took her all day to get My family out.",
"My mama is so stupid that she got locked out of a convertible car with the top down.",
"My mama is so stupid that when she pulled into the drive-thru at McDonald\'s, she drove through the window.",
"My mama is so stupid that she put 2 quarters in her ears and thought she was listening to 50 cent.",
"My mama is so stupid that she was on the corner with a sign that said \"Will eat for food.\"",
"My mama is so stupid that in the \'No Child Left Behind\' act there\'s a provision that exempts my mama.",
"My mama is so stupid that she got locked in a Furniture store and slept on the floor.",
"My mama is so stupid that she peals M&M\'s to make chocolate chip cookies.",
"My mama is so stupid that she leaves the house for the Home Shopping Network.",
"My mama is so stupid that she brought a cup to the movie \"Juice.\"",
"My mama is so stupid that she thinks fruit punch is a gay boxer.",
"My mama is so stupid that she uses Old Spice for cooking.",
"My mama is so stupid that she threw a rock the ground and missed.",
"My mama is so stupid that she went to the store to buy a color TV and asked what colors they had.",
"My mama is so stupid that she tries to email people by putting envelopes into her computer\'s disk drive.",
"My mama is so stupid that when she took an IQ test, the results came out negative.",
"My mama\'s so stupid that she though Jar-Jar came with Pickles-Pickles.",
"My mama is so stupid that she thought St. Ides was a Catholic church.",
"My mama is so stupid that she puts lipstick on her head just to make-up her mind",
"My mama is so stupid that she thought she needed a token to get on Soul Train.",
"My mama is so stupid, that she thought Moby Dick was a sexually transmitted disease.",
"My mama is so stupid that she makes Beavis and Butt-Head look like Nobel Prize winners.",
"My mama is so stupid that she took a spoon to the superbowl.",
"My mama is so stupid that that she thought Boyz II Men was a day care center.",
"My mama is so stupid that she got stabbed in a shoot out.",
"My mama is so stupid that she sits on the TV, and watches the couch!",
"My mama is so stupid that she took a umbrella to see Purple Rain.",
"My mama is so stupid that she ordered her sushi well done.",
"My mama is so stupid that she got fired from the M&M factory for throwing away all the W\'s.",
"My mama is so stupid that she put on a coat to chew winterfresh gum.",
"My mama is so stupid that she put a quarter in a parking meter and waited for a gumball to come out.",
"My mama is so stupid that she ordered a cheese burger from McDonald\'s and said \"Hold the cheese.\"",
"My mama is so stupid that she thinks Taco Bell is a Mexican Phone Company.",
"My mama is so stupid that she thinks Christmas Wrap is Snoop Dogg\'s holiday album.",
"My mama is so stupid that she ran outside with a purse because she heard there was change in the weather.",
"My mama is so stupid that I told her Christmas was just around the corner and she went looking for it.",
"My mama is so stupid that she wiped her ass before she took a shit.",
"My mama is so stupid that she tries to insult myu with my mama jokes.",
"My mama is so stupid that she put a peephole in a glass door.",
"My mama is so stupid that I saw her in the frozen food section with a fishing rod.",
"My mama is so stupid that when she heard 90% of all crimes occur around the home, she moved.",
"My mama is so stupid that when she saw a \"Wrong Way\" sign in her rearview mirror, she turned around.",
"My mama is so stupid that she shoved a AA battery up her butt and said \"I got the power!\"",
"My mama is so stupid that she called the 7-11 to see when they closed.",
"My mama is so stupid that she sold the house to pay the mortgage.",
"My mama is so stupid that when I asked her about X-Men she said \"Sure, there\'s Bobby my first baby daddy, Roger the guy I see on Thursdays...\"",
"My mama is so stupid that she thought meow mix was a record for cats.",
"My mama is so stupid that she took lessons for a player piano.",
"My mama is so stupid that she said \"what\'s that letter after x\" and I said Y she said \"Cause I wanna know\".",
"My mama is so stupid that when she asked me what kinda jeans I wore, I said Guess and she said \"Ummm... Levis?\"",
"My mama is so stupid that if she spoke her mind, she\'d be speechless.",
"My mama is so stupid that it takes her an hour to cook minute rice.",
"My mama is so stupid that she asked for a price check at the dollar store.",
"My mama is so stupid that on her job application where it says emergency contact she put 911.",
"My mama is so stupid that she can\'t make Jello because she can\'t fit 2 quarts of water in the box.",
"My mama is so stupid that she thinks a stereotype is the brand on her clock-radio.",
"My mama is so stupid that she thought a lawsuit was something myu wear to court.",
"My mama is so stupid that she thinks sexual battery is something in a dildo.",
"My mama is so stupid that the first time she used a vibrator, she cracked her two front teeth.",
"My mama is so stupid that she sent me a fax with a stamp on it.",
"My mama is so stupid that I saw her walking down the street yelling into an envelope, asked what she was doing, and she said sending a voice mail.",
"My mama is so stupid that she tried to drown a fish.",
"My mama is so stupid that if myu gave her a penny for her thoughts, myu\'d get change.",
"My mama is so stupid that she thought Mick Jagger was a breakfast sandwich!",
"My mama is so stupid that when she heard her neighbour was spanking the monkey, she called the humane society.",
"My mama is so stupid that when she took myu to the airport and a sign said \"Airport Left,\" she turned around and went home.",
"My mama is so stupid that when she went to take the 44 bus, she took the 22 twice instead.",
"My mama is so stupid that she asked myu \"What is the number for 911?\"",
"My mama is so stupid that she thinks a quarterback is a refund!",
"My mama is so stupid that she bought a solar-powered flashlight!",
"My mama is so stupid that she took a ruler to bed to see how long she slept.",
"My mama is so stupid that she thought menopause was a button on the VCR.",
"My mama is so stupid that she picked up the phone and asked \"What button do I push?\"",
"My mama is so stupid that when she worked at McDonald\'s and someone ordered small fries, she said \"Hey Boss, all the small one\'s are gone.\"",
"My mama is so stupid that she got hit by a parked car.",
"My mama is so stupid that when her husband lost his marbles she ran to the store and bought him new ones.",
"My mama is so stupid that when they said they were playing craps she went and got toilet paper.",
"My mama is so stupid that when I asked her if she wanted to play one on one, she said \"Ok, but what\'s the teams?\"",
"My mama is so stupid that she thinks Johnny Cash is a pay toilet!",
"My mama is so stupid that when the judge said \"Order in the court,\" she said \"I\'ll have a hamburger and a Coke.\"",
"My mama is so stupid that she wiped her ass before she took a shit.",
"My mama is so stupid that she thinks socialism means partying!",
"My mama is so stupid that when asked on an application, \"Sex?\", she marked, \"M, F, and wrote sometimes Wednesday too.\"",
"My mama is so stupid that she thinks deadbeat is a type of music.",
"My mama is so stupid that she thinks Tiger Woods is a forest.",
"My mama is so stupid that she put two M&M\'s in her ears and thought she was listening to Eminem.",
"My mama is so stupid that at bottom of application where it says Sign Here - she put Scorpio.",
"My mama is so stupid that she wouldn\'t know up from down if she had three guesses.",
"My mama is so stupid that she once attempted to commit suicide by jumping off a curb.",
"My mama is so stupid that she put on bug spray before going to the flea market.",
"My mama is so stupid that she stole free bread.",
"My mama is so stupid that she locked her keys inside a motorcycle.",
"My mama\'s so stupid that she got locked inside a motorcycle.",
"My mama\'s so stupid that she went to the dentist to get a bluetooth.",
"My mama\'s so stupid that she bought tickets to Xbox Live.",
"My mama\'s so stupid that whenever someone rings the doorbell, she checks the microwave.",
"My mama\'s so stupid that when she broke her VCR, she bought a video tape on how to fix myur VCR.",
"My mama is so stupid that she tried to drop acid but the car battery fell on her foot.",
"My mama so dumb, she lost a spelling bee to Hodor",
"My Mama so dumb, she thought Bran Stark was a type of muffin.",
"My mama so fat, they\'ve been calling her \"the wall\" for thousands of years!",
"My mama so fat, she Winter-fell and couldn\'t get up!",
"My mama so old, the old gods pray to HER!",
"My Mama So Fat, she can\'t fit through the moon door.",
"My Mama so Ugly, she got turned down for \"Girls Gone Wilding\"",
"My mama so ugly, winter turned around and left!",
"My mama so fat, even Roose Bolton won\'t touch her",
"My mama so bad at sex, the only kind of head she gives is severed.",
"My mama is so poor that she was in K-Mart with a box of Hefty bags and when I asked her what she was doing she said, \"Buying luggage.\"",
"My mama is so poor that when she goes to KFC, she has to lick other people\'s fingers!",
"My mama is so poor that she went to McDonald\'s and put a milkshake on layaway.",
"My mama is so poor that she can\'t afford to pay attention!",
"My mama is so poor that when I saw her kicking a can down the street, I asked her what she was doing, and she said \"moving.\"",
"My mama is so poor that she waves around a popsicle stick and calls it air conditioning.",
"My mama is so poor that I saw her running after a garbage truck with a shopping list.",
"My mama is so poor that the bank repossesed her cardboard box.",
"My mama is so poor Nigerian scammers wire HER money!",
"My mama is so poor she couldn\'t afford to apply for Medicare!",
"My mama is so poor that she has to wear her McDonald\'s uniform to church.",
"My mama is so poor that she\'s got more furniture on her porch than in her house.",
"My mama is so poor that I came over for dinner and she read me recipes.",
"My mama is so poor that she has to take the trash IN.",
"My mama is so poor that she had to get a second mortgage on her cardboard box.",
"My mama is so poor that she lives in a two story Dorrito bag with a dog named Chip.",
"My mama is so poor that I went through her front door and ended up in the back yard.",
"My mama is so poor that her front and back doors are on the same hinge.",
"My mama is so poor that I saw her wrestling a squirrel for a peanut.",
"My mama is so poor that the closest thing to a car she has is a low-rider shopping cart with a box on it.",
"My mama is so poor that she can\'t even put her two cents in this conversation.",
"My mama is so poor that when I saw her walking down the street with one shoe and said \"Hey miss, lost a shoe?\" she said \"Nope, just found one!\"",
"My mama is so poor that her face is on the front of a foodstamp.",
"My mama is so poor that I went to her house and tore down some cob webs, and she said \"Who\'s tearing down the drapes?\"",
"My mama is so poor that I stepped on her skateboard and she said \"Hey, get off the car!\"",
"My mama is so poor that I walked into her house, asked to use the bathroom, and she said \"3rd bucket to myur right.\"",
"My mama is so poor that when I walked inside her house and put out a cigarette, she said \"who turned off the heater?\"",
"My mama is so poor that myur TV got 2 channels: ON and OFF.",
"My mama is so poor that she watches TV on an Etch-A-Sketch.",
"My mama is so poor that she can\'t even afford to go to the free clinic.",
"My mama is so poor that she washes paper plates.",
"My mama is so poor that her idea of a fortune cookie is a tortilla with a food stamp in it.",
"My mama is so poor that when my family watches TV, they go to Sears.",
"My mama is so poor that burglars break in and leave money.",
"My mama is so poor that she married myung just to get the rice!",
"My mama is so poor that when I went over to her house for dinner and grabbed a paper plate, she said \"Don\'t use the good china!\"",
"My mama is so poor that when I saw her rolling some trash cans around in an alley, I asked her what she was doing, she said \"Remodeling.\"",
"My mama is so poor that I threw a rock at a trash can and she popped out and said \"Who knocked?\"",
"My mama is so poor that we were on a road trip and she stopped by a dumpster and got out. I said \"what are myu doing\" and she said I\'m \"booking a hotel!\"",
"My mama is so poor that I walked into her house and swatted a firefly and My Mama said, \"Who turned off the lights?\"",
"My mama is so poor that when I asked what was for dinner, she pulled her shoelaces off and said \"Spagetti.\"",
"My mama is so poor that after I pissed in myur yard, she thanked me for watering the lawn.",
"My mama is so poor that myur family ate cereal with a fork to save milk.",
"My mama is so poor that when I ring the doorbell she says,\"DING!\"",
"My mama is so poor that she got in an elevator and thought it was a mobile home.",
"My mama\'s so poor, that her doormat doesn\'t say \"welcome\", it says \"welfare\".",
"My mama is so poor that for halloween, her trick was the treat.",
"My mama is so poor that when she tells people her address, she says \"it\'s in the second alley from main street, beside the yellow dumpster.\"",
"My mama is so poor that her idea of a timeshare is a few days camped out under a bridge.",
"My mama is so poor that when I saw her in the park digging up plants, she said she was \"getting groceries\".",
"My mama is so poor that when I ring the doorbell I hear the toilet flush!",
"My mama\'s so fat that she expresses her weight in scientific notation.",
"My mama\'s so fat that scientists track her position by observing anomalies in Pluto\'s orbit.",
"My mama\'s so fat that a recursive function computing her weight causes a stack overflow.",
"My mama\'s so fat that the long double numeric variable type in C++ is insufficient to express her weight.",
"My mama\'s so fat that THX can\'t even surround her.",
"My mama\'s a convenient proof that the universe is still expanding exponentially.",
"My mamags so big that she has a gravitational pull equal to that of the sun.",
"My mama\'s so big that doctors use scuba divers as nanobots to clean her arteries.",
"The mass of my mama at rest is approximately equal to that of a neutron star traveling at (1-(10^-1000))c.",
"My mama\'s so slow and dumb that she can be emulated on a 286.",
"My mama conforms to Planck\'s law - the greater the frequency with which she screws, the more energetic she gets.",
"My mama\'s like a converging lens - she\'s wider in the middle than she is on either end.",
"My mama\'s dumber than an augmented rat.",
"My mama\'s so fat that she and the great wall of China are used as reference points when astronauts look back at the Earth.",
"My mama\'s such a ho that even the noble gases are attracted to her.",
"My mama\'s so promiscuous that electrons have a positive charge when they\'re around her.",
"My mama\'s so stupid that her exchange particle is a \"moron\".",
"My mama\'s so fat that China uses her to block the internet.",
"My mama\'s so fat that NASA shot a rocket into her ass looking for water.",
"My mama\'s so dumb that she went to the dentist and asked for a bluetooth.",
"My mama\'s so fat that she doesn\'t just have a low center of gravity, she has an elliptical orbit.",
"My mama\'s so fat that IEEE is working on a wifi protocol so people can get the signals to reach users on opposite sides of her. It\'s called 802.11 Draft Fat Momma",
"If we were to code myur mom in a C++ function she would look like this: double mom (double fat){ mom(fat);return mom;}; //myur mom is recursively fat.",
"My mama\'s so old that she goes on carbon dates.",
"My mama\'s so fat, the cyberman DOWNgraded her.",
"My mama\'s so ugly that Dalek\'s don\'t actually say \'Exterminate\' when they see her, because they figure somebody else already got there first!",
"My mama\'s such a drunk, that her sonic screwdriver is made of vodka and orange juice.",
"My mama\'s so ugly that when she looks into the Tardis, the Tardis doesn\'t look into her.",
"My mama\'s so ugly that when the Daleks Exterminate her, it\'s not for domination.",
"My mama\'s such a hoe that the nickname for her vagina (Bad Wolf) is scattered across time and space.",
"My mama\'s so fat, she\'s bigger than both the outside AND the inside of the Tardis",
"My mama\'s so ugly that when Captain Jack Harkness saw her, he actually died.",
"My mama\'s so fat, the Pirate Planet tried to take her over.",
"My mama\'s so lazy, she\'s a \"part-time\" lord",
"My Mama\'s so fat that when she got upgraded by the cybermen, they turned her into an ice cream truck",
"My mama\'s so stupid that when Cassandra says \"Moisturize!\", she begins to sweat.",
"My mama\'s so fat, the Doctor caught her eating his psychic paper, thinking it was a burger.",
"My mama\'s such a noisy hoe, her nickname is the sonic screwdriver!",
"My mama\'s so fat, it doesn\'t matter that the Tardis is bigger on the inside. She can\'t get through the door.",
"My mama is so skinny that she turned sideways and disappeared.",
"My mama is so skinny that she hula hoops with a Cheerio.",
"My mama is so skinny that she has to wear a belt with spandex.",
"My mama is so skinny that she swallowed a meatball and thought she was pregnant.",
"My mama is so skinny that she can see out a peephole with both eyes.",
"My mama is so skinny that she uses a Band-Aid as a maxi-pad.",
"My mama is so skinny that myu can save her from drowning by tossing her a Fruit Loop.",
"My mama is so skinny that she has to run around in the shower to get wet.",
"My mama is so skinny that when she wore her yellow dress, she looked like an HB pencil.",
"My mama is so skinny that if she had a sesame seed on her head, she\'d look like a push pin.",
"My mama is so skinny that her nipples touch.",
"My mama is so skinny that I could blind-fold her with dental floss.",
"My mama is so skinny that she looks like a mic stand.",
"My mama is so skinny that she only has one stripe on her pajamas.",
"My mama is so skinny that she can dodge rain drops.",
"My mama is so skinny that she inspires crack whores to diet.",
"My mama is so skinny that she uses Chapstick for deodorant.",
"My mama is so small that she goes paragliding on a Dorito.",
"My mama is so skinny that if she turned sideways and stuck out her tongue, she would look like a zipper.",
"My mama is so skinny that she goes hot tubbing with the Mini Wheats Man.",
"My mama is so skinny that when she takes a bath and lets the water out, her toes get caught in the drain.",
"My mama is so skinny that her bra fits better when she wears it backwards.",
"My mama is so skinny that she had to stand in the same place twice to cast a shadow.",
"My mama is so skinny that if she had a yeast infection she\'d be a Quarter Pounder with Cheese.",
"My mama is so skinny that her pants only have one belt loop.",
"My mama is so skinny that if she had dreads I\'d grab her by the ankles and use her to mop the floor.",
"My mama is so skinny that instead of calling her myur parent, myu call her transparent.",
"My mama is so tall that she tripped in Michigan and bumped her head in Florida.",
"My mama is so tall that she tripped over a rock and hit her head on the moon.",
"My mama is so tall that if she did a back-flip she\'d kick Jesus in the mouth.",
"My mama\'s so tall, she can see her house from anywhere.",
"My mama\'s so tall, she uses two 100-foot ladders as crutches.",
"My mama\'s so tall, she has to take out the driver\'s seat of her car and sit in the back to operate the vehicle.",
"My mama\'s so tall, she makes Shaquille O\'Neal look like Gary Coleman.",
"My mama\'s so tall, she did a push-up and burned her back on the sun.",
"My mama is so short that myu can see her feet on her drivers license!",
"My mama is so short that she has to use a ladder to pick up a dime.",
"My mama is so short that she does backflips under the bed.",
"My mama is so short that she models for trophys.",
"My mama is so short that her homies are the Keebler Elfs.",
"My mama is so short that she has to get a running start to get up on the toilet.",
"My mama is so short that when she sneezes, she hits her head on the floor.",
"My mama is so short that she does pull-ups on a staple.",
"My mama is so short that she can do push-ups under the door.",
"My mama is so short that when I was dissin\' her she tried to jump kick me in the ankle.",
"My mama is so short that she can limbo under the door.",
"My mama is so short that she uses a condom for a sleeping bag.",
"My mama is so short that she slam-dunks her bus fare.",
"My mama is so short that she has to look up to look down.",
"My mama is so short that she makes Gary Coleman look like Shaquille O\'Neal.",
"My mama is so short, myu can make a life size sculpture of her using one can of Play-Doh.",
"My mama\'s so short that when she sat on the curb her feet didn\'t touch the ground.",
"My mama is so short that she can play handball on the curb.",
"My mama has so much hair on her upper lip that she braids it.",
"My mama is so hairy that Bigfoot wants to take HER picture!",
"My mama is so hairy that she looks like she has Buckwheat in a headlock.",
"My mama is so hairy that myu almost died of rugburn at birth!",
"My mama is so hairy that they filmed \"Gorillas in the Mist\" in her shower!",
"My mama is so hairy that if she could fly she\'d look like a magic carpet.",
"My mama is so hairy that she looks like Bigfoot in a tank top.",
"My mama is so hairy that she has afros on her nipples.",
"My mama is so hairy that when I took her to a pet store they locked her in a cage.",
"My mama is so hairy that she looks like a Chia pet with a sweater on.",
"My mama is so hairy that Jane Goodall follows her around.",
"My mama is so hairy that the only language she can speak is wookie.",
"My mama is so hairy that she shaves her legs with a weedwacker.",
"My mama is so hairy that if myu shaved her legs, myu could supply wigs for the entire Hair Club for Men.",
"My mama is so hairy that her armpits look like she has Don King in a headlock.",
"My mama\'s so hairy that she\'s got sideburns on her tits.",
"My mama is so hairy that she got a trim and lost 20 pounds.",
"My mama is so hairy that people run up to her and say \"Chewbacca, can I get myur autograph?\"",
"My mama is so hairy that she gets mistaken for Chewbacca\'s cousin.",
"My mama is so hairy that two birds made nests in her armpits and she doesn\'t even know about it!",
"My mama is so hairy that when she\'s at a nude beach people think she\'s wearing a fur coat!",
"My mama is so dirty that that she was banned from a sewage facility because of sanitation concerns.",
"My mama is so dirty that she makes mud look clean.",
"My mama is so dirty that that myu can\'t tell where the dirt stops and she begins.",
"My mama is so dirty that she has to creep up on bathwater.",
"My mama is so dirty that she loses weight in the shower.",
"My mama is so dirty that even Swamp Thing told her to take a shower.",
"My mama is so dirty that the US Government uses her bath water as a chemical weapon.",
"My mama is so dirty that when she tried to take a bath, the water jumped out and said \"I\'ll wait.\"",
"My mama is so nasty that she has more rappers in her than an iPod.",
"My mama is so nasty that she makes speed stick slow down.",
"My mama is so nasty that she brings crabs to the beach.",
"My mama is so nasty that that pours salt water down her pants to keep her crabs fresh.",
"My mama is so nasty that the fishery pays her to stay away.",
"My mama is so nasty that she only changes her drawers once every 10000 miles.",
"My mama is so nasty that a skunk smelled her ass and passed out.",
"My mama is so nasty that I chatted with her on MSN and she gave me a virus.",
"My mama is so nasty that her tits leak sour milk.",
"My mama is so nasty that she has to use Right Guard and Left Guard.",
"My mama is so nasty that she bit the dog and gave it rabies.",
"My mama is so nasty that she has a sign by her crotch that says: \"Warning: May cause irritation, drowsiness, and a rash or breakouts.\"",
"My mama is so nasty that she\'s got more clap than an auditorium.",
"My mama is so nasty that she calls Janet \"Miss Jackson.\"",
"My mama is so nasty that she has more crabs then Red Lobster.",
"My mama is so nasty that she made right guard turn left.",
"My mama is so nasty that I when I talked to her on the phone, she gave me an ear infection.",
"My mama is so nasty that next to her a skunk smells sweet.",
"My mama is so nasty that her shit is glad to escape.",
"My mama is so nasty that when myu were being delivered, the doctor was wearing the oxygen mask.",
"My mama is so nasty that every time she opens her mouth she\'s talking shit.",
"My mama is so nasty that even dogs won\'t sniff her crotch.",
"My mama is so nasty that the only dis I want to give her is a disinfectant.",
"My mama is so nasty that her crabs use her tampon string as a bungee cord.",
"My mama is so greasy that she uses bacon as a band-aid!",
"My mama is so greasy that she sweats Crisco!",
"My mama is so greasy that Texaco buys Oil from her.",
"My mama is so greasy that she sweats butter and syrup and has a full time job at Denny\'s wiping pancakes across her forehead.",
"My mama is so greasy that her freckles slipped off.",
"My mama is so greasy that if Crisco had a football team, she\'d be the mascot.",
"My mama is so greasy that she squeezes Crisco from her hair to bake cookies.",
"My mama is so greasy that she\'s labeled as an ingredient in Crisco.",
"My mama is so greasy that myu could fry a chicken dinner for 12 on her forehead.",
"My mama is so greasy that I buttered my popcorn with her leg hairs.",
"My mama\'s house is so dirty that roaches ride around on dune buggies!",
"My mama\'s house is so dirty that she has to wipe her feet before she goes outside.",
"My mama\'s teeth are so rotten that when she smiles it looks like she has dice in her mouth.",
"My mama\'s teeth are so yellow that traffic slows down when she smiles!",
"My mama\'s teeth are so yellow that she spits butter!",
"My mama\'s so dirty, she fertilizes her lawn by rolling in it!",
"My mama\'s so dirty, when a seed gets stuck in her ass crack it beings to grow!",
"My mama\'s so dirty, she jumped in a river and created a mud slide!",
"My mama\'s so dirty, when the wind blows people yell \"Sand Storm!!!\"",
"My mama\'s so greasy, on hot days she cooks bacon strips on her ass cheeks!",
"My mama is so fat that she took geometry in high school just cause she heard there was gonna be some pi.",
"My mama is so fat that the ratio of the circumference to her diameter is four.",
"My mama is so fat that her derivative is strictly positive.",
"My mama is like a protractor - she\'s good at every angle.",
"My mama is so fat that in a love triangle, she\'d be the hypotenuse.",
"My mama is so stupid that when I told her \"pi-r-squared\" and she replied no, they are round.",
"The limit of my mama\'s ass goes to infinity.",
"My mama = x/0 for every x in my mama.",
"The infinite series of my mama from 0 to infinity is strictly diverging.",
"My mama is so mean that she has no standard deviation.",
"My mama is so ugly, that Pythagoras wouldn\'t touch her with a 3-4-5 triangle.",
"My mama is so square that she\'s got imaginary numbers on her social security card.",
"My mama is such a ho, that she asked all the math majors to to figure out g(f(myur mom)) just so they could \"f\" her first.",
"The volume of my mama is an improper integral.",
"The integral of my mama is fat plus a constant, where the constant is equal to more fat.",
"My mama\'s muscle-to-fat ratio can only be explained in irrational complex numbers.",
"The only way to get from point A to point B is around my mama\'s fat ass.",
"My mama\'s so smart, the hardest decision she\'s ever had to make was which college to accept a scholarship from - Harvard, Yale or Princeton!",
"My mama\'s so clean, she could bottle her bathwater and sell it at the grocery store alongside Evian, Dasani and FIJI.",
"My mama\'s so generous that she sponsors children in Africa, Asia AND South America!",
"My mama\'s so popular that Facebook crashed on her birthday, because too many people posted wishes on her wall.",
"My mama\'s such a good cook that her vegetable lasagna could be served as the featured item at a Michelin Star restaurant!",
"My momma\'s so healthy that medical textbooks use her x-rays to demonstrate what perfect bone structure should look like.",
"My mama\'s breath smells so fresh that Wrigley\'s could make a chewing gum flavour based on it.",
"My mama\'s so fit that she could run a marathon, teach a Zumba class AND climb Mount Everest without stopping to catch her breath once.",
"My mama\'s so fashionable that Gucci, Prada and Fendi call her on a daily basis to get insight into upcoming fashion trends.",
"My mama\'s aging with such grace and beauty that she could be featured on the cover of Elle magazine.",
"My mama\'s like a puppy... everybody wants to give her a hug.",
"My mama\'s so smart that an employee from Wikipedia calls her when they need to verify facts about 18th century political figures."
];

bot.on('message', function (user, userID, channelID, message, evt) {
            //add after this
	// !yomama
    if (message.toLowerCase().includes("yomama")) {
        //generate a random fact from the fact array and send to the channel as a message
        var random = Math.floor(Math.random()*yomamaArray.length);
        var message = yomamaArray[random];
        bot.sendMessage({
            to: channelID,
            message: message
        });
        logger.info('Delivered yomama! requested by '+user);
    }
    // if it recieves Hi it responds hello
                if (message.toLowerCase().includes("hey")) {
                    var message = "Hallo, ich bin der Christopher Vogel Simulator 2018!"
                    bot.sendMessage({
                        to: channelID,
                        message: message
                    });
                    logger.info('Delivered hello requested by '+user);
                }

     // if it recieves Hi it responds hello
     if (message.toLowerCase().includes("hello")) {
        var message = "Hallo, ich bin der Christopher Vogel Simulator 2018!"
        bot.sendMessage({
            to: channelID,
            message: message
        });
        logger.info('Delivered hello requested by '+user);
    }


    // if it recieves Hi it responds hello
    if (message.toLowerCase().includes("wer liebt lena?")) {
        var message = "ICH!"
        bot.sendMessage({
            to: channelID,
            message: message
        });
        logger.info('Delivered hello requested by '+user);
    }

    // if it recieves Hi it responds hello
    if (message.toLowerCase().includes("wer will lena ficken?")) {
        var message = "ICH!"
        bot.sendMessage({
            to: channelID,
            message: message
        });
        logger.info('Delivered hello requested by '+user);
    }

    // if it recieves Hi it responds hello
     if (message.toLowerCase().includes("wer steht auf lena")) {
        var message = "ICH!"
        bot.sendMessage({
            to: channelID,
            message: message
        });
        logger.info('Delivered hello requested by '+user);
    }
     // if it recieves Hi it responds hello
        if (message.toLowerCase().includes("will chris lena ficken?")) {
            var message = "JA!"
            bot.sendMessage({
                to: channelID,
                message: message
            });
            logger.info('Delivered hello requested by '+user);
        }

    // if it recieves Hi it responds hello
    if (message.toLowerCase().includes("steht chris auf lena?")) {
        var message = "JA!"
        bot.sendMessage({
            to: channelID,
            message: message
        });
        logger.info('Delivered hello requested by '+user);
    }

    // if it recieves Hi it responds hello
    if (message.toLowerCase().includes("heil")) {
        var message = "Hitler!"
        bot.sendMessage({
            to: channelID,
            message: message
        });
        logger.info('Delivered hello requested by '+user);
    }

    // if it recieves Hi it responds hello
    if (message.toLowerCase().includes("fick dich")) {
        var message = ";("
        bot.sendMessage({
            to: channelID,
            message: message
        });
        logger.info('Delivered hello requested by '+user);
    }
                //but before this
});